### PR TITLE
#49: workaround for sample metadata to be harvested

### PR DESCRIPTION
**Pull request by etj**
Change URL from gist to http://dgiwg.geo-solutions.it/test/metadata/DMFMetadataRecord.xml, which properly returns `text/xml` as content-type.

### CODE REVIEW

**Comment by dstenger** [comment]
As the test will be maintained by OGC CITE team, we don't think it is a good idea to include resources which are not under control of CITE team.

Thus, we propose to put the file somewhere else.
Could site documentation on github.io be a possible place to make the file available?
https://opengeospatial.github.io/ets-cat20-dgiwg10/

**Comment by etj** [comment]
It's ok as long as the returned content-type for the file is `text/xml`

**Comment by dstenger** [comment]
@etj 
Can you please check if fix #53 works for you (is already merged into master branch)?
If this is the case, this pull request can be closed.

**Comment by lgoltz** [comment]
Resource http://dgiwg.geo-solutions.it/test/metadata/DMFMetadataRecord.xml is not available

**Pull request closed without merging**
